// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	proto/auth/auth.proto

It has these top-level messages:
	User
	Request
	IsNewDB
	ResponseUser
	ResponseRole
	ResponseMenu
	ResponseRule
	ResponseForm
	ResponseFormSchema
	ResponseToken
	Token
	Error
	Role
	Rules
	Conditions
	Menu
	Badge
	Wrapper
	Atributes
	Form
	FormSchema
	Buttons
	Class
	SelectOptions
	Values
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	// @inject_tag: gorm:"primary_key"
	Idcode  string `protobuf:"bytes,1,opt,name=idcode" json:"idcode,omitempty" gorm:"primary_key"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Company string `protobuf:"bytes,3,opt,name=company" json:"company,omitempty"`
	// @inject_tag: gorm:"unique;not null"
	Email    string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty" gorm:"unique;notnull"`
	Password string `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	Token    string `protobuf:"bytes,6,opt,name=token" json:"token,omitempty"`
	// @inject_tag: gorm:"many2many:user_roles;foreignkey:idcode;association_foreignkey:idcode;association_jointable_foreignkey:role_idcode;jointable_foreignkey:user_idcode;"
	Roles    []*Role `protobuf:"bytes,7,rep,name=roles" json:"roles,omitempty" gorm:"many2many:user_roles;foreignkey:idcode;association_foreignkey:idcode;association_jointable_foreignkey:role_idcode;jointable_foreignkey:user_idcode;"`
	Designer bool    `protobuf:"varint,8,opt,name=designer" json:"designer,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetIdcode() string {
	if m != nil {
		return m.Idcode
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *User) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *User) GetDesigner() bool {
	if m != nil {
		return m.Designer
	}
	return false
}

type Request struct {
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type IsNewDB struct {
	Isnew bool `protobuf:"varint,1,opt,name=isnew" json:"isnew,omitempty"`
}

func (m *IsNewDB) Reset()                    { *m = IsNewDB{} }
func (m *IsNewDB) String() string            { return proto.CompactTextString(m) }
func (*IsNewDB) ProtoMessage()               {}
func (*IsNewDB) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IsNewDB) GetIsnew() bool {
	if m != nil {
		return m.Isnew
	}
	return false
}

type ResponseUser struct {
	User   *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Users  []*User  `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
	Token  *Token   `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
	Menues []*Menu  `protobuf:"bytes,5,rep,name=menues" json:"menues,omitempty"`
	Rules  []*Rules `protobuf:"bytes,6,rep,name=rules" json:"rules,omitempty"`
}

func (m *ResponseUser) Reset()                    { *m = ResponseUser{} }
func (m *ResponseUser) String() string            { return proto.CompactTextString(m) }
func (*ResponseUser) ProtoMessage()               {}
func (*ResponseUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ResponseUser) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ResponseUser) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ResponseUser) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *ResponseUser) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *ResponseUser) GetMenues() []*Menu {
	if m != nil {
		return m.Menues
	}
	return nil
}

func (m *ResponseUser) GetRules() []*Rules {
	if m != nil {
		return m.Rules
	}
	return nil
}

type ResponseRole struct {
	Role   *Role    `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	Roles  []*Role  `protobuf:"bytes,2,rep,name=roles" json:"roles,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *ResponseRole) Reset()                    { *m = ResponseRole{} }
func (m *ResponseRole) String() string            { return proto.CompactTextString(m) }
func (*ResponseRole) ProtoMessage()               {}
func (*ResponseRole) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ResponseRole) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *ResponseRole) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *ResponseRole) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ResponseMenu struct {
	Menu   *Menu    `protobuf:"bytes,1,opt,name=menu" json:"menu,omitempty"`
	Menues []*Menu  `protobuf:"bytes,2,rep,name=menues" json:"menues,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *ResponseMenu) Reset()                    { *m = ResponseMenu{} }
func (m *ResponseMenu) String() string            { return proto.CompactTextString(m) }
func (*ResponseMenu) ProtoMessage()               {}
func (*ResponseMenu) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ResponseMenu) GetMenu() *Menu {
	if m != nil {
		return m.Menu
	}
	return nil
}

func (m *ResponseMenu) GetMenues() []*Menu {
	if m != nil {
		return m.Menues
	}
	return nil
}

func (m *ResponseMenu) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ResponseRule struct {
	Rule   *Rules   `protobuf:"bytes,1,opt,name=rule" json:"rule,omitempty"`
	Rules  []*Rules `protobuf:"bytes,2,rep,name=rules" json:"rules,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *ResponseRule) Reset()                    { *m = ResponseRule{} }
func (m *ResponseRule) String() string            { return proto.CompactTextString(m) }
func (*ResponseRule) ProtoMessage()               {}
func (*ResponseRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ResponseRule) GetRule() *Rules {
	if m != nil {
		return m.Rule
	}
	return nil
}

func (m *ResponseRule) GetRules() []*Rules {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *ResponseRule) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ResponseForm struct {
	Form   *Form    `protobuf:"bytes,1,opt,name=form" json:"form,omitempty"`
	Forms  []*Form  `protobuf:"bytes,2,rep,name=forms" json:"forms,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *ResponseForm) Reset()                    { *m = ResponseForm{} }
func (m *ResponseForm) String() string            { return proto.CompactTextString(m) }
func (*ResponseForm) ProtoMessage()               {}
func (*ResponseForm) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ResponseForm) GetForm() *Form {
	if m != nil {
		return m.Form
	}
	return nil
}

func (m *ResponseForm) GetForms() []*Form {
	if m != nil {
		return m.Forms
	}
	return nil
}

func (m *ResponseForm) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ResponseFormSchema struct {
	Formschema  *FormSchema   `protobuf:"bytes,1,opt,name=formschema" json:"formschema,omitempty"`
	Formschemas []*FormSchema `protobuf:"bytes,2,rep,name=formschemas" json:"formschemas,omitempty"`
	Errors      []*Error      `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *ResponseFormSchema) Reset()                    { *m = ResponseFormSchema{} }
func (m *ResponseFormSchema) String() string            { return proto.CompactTextString(m) }
func (*ResponseFormSchema) ProtoMessage()               {}
func (*ResponseFormSchema) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ResponseFormSchema) GetFormschema() *FormSchema {
	if m != nil {
		return m.Formschema
	}
	return nil
}

func (m *ResponseFormSchema) GetFormschemas() []*FormSchema {
	if m != nil {
		return m.Formschemas
	}
	return nil
}

func (m *ResponseFormSchema) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ResponseToken struct {
	Token  *Token   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	User   *User    `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *ResponseToken) Reset()                    { *m = ResponseToken{} }
func (m *ResponseToken) String() string            { return proto.CompactTextString(m) }
func (*ResponseToken) ProtoMessage()               {}
func (*ResponseToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ResponseToken) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *ResponseToken) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ResponseToken) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Token struct {
	Token  string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Valid  bool     `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	// @inject_tag: gorm:"primary_key"
	Idcode      int32  `protobuf:"varint,1,opt,name=idcode" json:"idcode,omitempty" gorm:"primary_key"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Error) GetIdcode() int32 {
	if m != nil {
		return m.Idcode
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Role struct {
	// @inject_tag: gorm:"primary_key"
	Idcode string `protobuf:"bytes,1,opt,name=idcode" json:"idcode,omitempty" gorm:"primary_key"`
	// @inject_tag: gorm:"unique;not null"
	Name  string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty" gorm:"unique;notnull"`
	Users []*User `protobuf:"bytes,3,rep,name=users" json:"users,omitempty"`
	// @inject_tag: gorm:"many2many:role_menus;foreignkey:idcode;association_foreignkey:idcode;association_jointable_foreignkey:menu_idcode;jointable_foreignkey:role_idcode;"
	Menues []*Menu `protobuf:"bytes,4,rep,name=menues" json:"menues,omitempty" gorm:"many2many:role_menus;foreignkey:idcode;association_foreignkey:idcode;association_jointable_foreignkey:menu_idcode;jointable_foreignkey:role_idcode;"`
	// @inject_tag: `gorm:"foreignkey:rolesrefer"`
	Rules []*Rules `protobuf:"bytes,5,rep,name=rules" json:"rules,omitempty" gorm:"foreignkey:rolesrefer"`
}

func (m *Role) Reset()                    { *m = Role{} }
func (m *Role) String() string            { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()               {}
func (*Role) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Role) GetIdcode() string {
	if m != nil {
		return m.Idcode
	}
	return ""
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Role) GetMenues() []*Menu {
	if m != nil {
		return m.Menues
	}
	return nil
}

func (m *Role) GetRules() []*Rules {
	if m != nil {
		return m.Rules
	}
	return nil
}

type Rules struct {
	// @inject_tag: gorm:"primary_key"
	Idcode     string      `protobuf:"bytes,1,opt,name=idcode" json:"idcode,omitempty" gorm:"primary_key"`
	Actions    string      `protobuf:"bytes,2,opt,name=actions" json:"actions,omitempty"`
	Subject    string      `protobuf:"bytes,3,opt,name=subject" json:"subject,omitempty"`
	Fields     string      `protobuf:"bytes,4,opt,name=fields" json:"fields,omitempty"`
	Conditions *Conditions `protobuf:"bytes,5,opt,name=conditions" json:"conditions,omitempty"`
	Rolesrefer string      `protobuf:"bytes,6,opt,name=rolesrefer" json:"rolesrefer,omitempty"`
}

func (m *Rules) Reset()                    { *m = Rules{} }
func (m *Rules) String() string            { return proto.CompactTextString(m) }
func (*Rules) ProtoMessage()               {}
func (*Rules) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Rules) GetIdcode() string {
	if m != nil {
		return m.Idcode
	}
	return ""
}

func (m *Rules) GetActions() string {
	if m != nil {
		return m.Actions
	}
	return ""
}

func (m *Rules) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Rules) GetFields() string {
	if m != nil {
		return m.Fields
	}
	return ""
}

func (m *Rules) GetConditions() *Conditions {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *Rules) GetRolesrefer() string {
	if m != nil {
		return m.Rolesrefer
	}
	return ""
}

type Conditions struct {
	// @inject_tag: gorm:"primary_key"
	Idcode     string   `protobuf:"bytes,1,opt,name=idcode" json:"idcode,omitempty" gorm:"primary_key"`
	Conditions []string `protobuf:"bytes,2,rep,name=conditions" json:"conditions,omitempty"`
}

func (m *Conditions) Reset()                    { *m = Conditions{} }
func (m *Conditions) String() string            { return proto.CompactTextString(m) }
func (*Conditions) ProtoMessage()               {}
func (*Conditions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Conditions) GetIdcode() string {
	if m != nil {
		return m.Idcode
	}
	return ""
}

func (m *Conditions) GetConditions() []string {
	if m != nil {
		return m.Conditions
	}
	return nil
}

type Menu struct {
	// @inject_tag: gorm:"primary_key"
	Idcode string `protobuf:"bytes,1,opt,name=idcode" json:"idcode,omitempty" gorm:"primary_key"`
	// @inject_tag: gorm:"unique;not null"
	Name    string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty" gorm:"unique;notnull"`
	Url     string   `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Badge   *Badge   `protobuf:"bytes,4,opt,name=badge" json:"badge,omitempty"`
	Wrapper *Wrapper `protobuf:"bytes,5,opt,name=wrapper" json:"wrapper,omitempty"`
	Title   bool     `protobuf:"varint,6,opt,name=title" json:"title,omitempty"`
	// @inject_tag: gorm:"many2many:menu_childrens;foreignkey:idcode;association_foreignkey:idcode;association_jointable_foreignkey:children_idcode;jointable_foreignkey:parent_idcode;"
	Children  []*Menu `protobuf:"bytes,7,rep,name=children" json:"children,omitempty" gorm:"many2many:menu_childrens;foreignkey:idcode;association_foreignkey:idcode;association_jointable_foreignkey:children_idcode;jointable_foreignkey:parent_idcode;"`
	Icon      string  `protobuf:"bytes,8,opt,name=icon" json:"icon,omitempty"`
	Roles     []*Role `protobuf:"bytes,9,rep,name=roles" json:"roles,omitempty"`
	BadgeID   string  `protobuf:"bytes,10,opt,name=badgeID" json:"badgeID,omitempty"`
	WrapperID string  `protobuf:"bytes,11,opt,name=wrapperID" json:"wrapperID,omitempty"`
}

func (m *Menu) Reset()                    { *m = Menu{} }
func (m *Menu) String() string            { return proto.CompactTextString(m) }
func (*Menu) ProtoMessage()               {}
func (*Menu) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Menu) GetIdcode() string {
	if m != nil {
		return m.Idcode
	}
	return ""
}

func (m *Menu) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Menu) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Menu) GetBadge() *Badge {
	if m != nil {
		return m.Badge
	}
	return nil
}

func (m *Menu) GetWrapper() *Wrapper {
	if m != nil {
		return m.Wrapper
	}
	return nil
}

func (m *Menu) GetTitle() bool {
	if m != nil {
		return m.Title
	}
	return false
}

func (m *Menu) GetChildren() []*Menu {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *Menu) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Menu) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Menu) GetBadgeID() string {
	if m != nil {
		return m.BadgeID
	}
	return ""
}

func (m *Menu) GetWrapperID() string {
	if m != nil {
		return m.WrapperID
	}
	return ""
}

type Badge struct {
	// @inject_tag: gorm:"primary_key"
	Idcode  string `protobuf:"bytes,1,opt,name=idcode" json:"idcode,omitempty" gorm:"primary_key"`
	Variant string `protobuf:"bytes,2,opt,name=variant" json:"variant,omitempty"`
	Text    string `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
}

func (m *Badge) Reset()                    { *m = Badge{} }
func (m *Badge) String() string            { return proto.CompactTextString(m) }
func (*Badge) ProtoMessage()               {}
func (*Badge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Badge) GetIdcode() string {
	if m != nil {
		return m.Idcode
	}
	return ""
}

func (m *Badge) GetVariant() string {
	if m != nil {
		return m.Variant
	}
	return ""
}

func (m *Badge) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Wrapper struct {
	// @inject_tag: gorm:"primary_key"
	Idcode      string     `protobuf:"bytes,1,opt,name=idcode" json:"idcode,omitempty" gorm:"primary_key"`
	Element     string     `protobuf:"bytes,2,opt,name=element" json:"element,omitempty"`
	Atributes   *Atributes `protobuf:"bytes,3,opt,name=atributes" json:"atributes,omitempty"`
	AtributesID string     `protobuf:"bytes,4,opt,name=atributesID" json:"atributesID,omitempty"`
}

func (m *Wrapper) Reset()                    { *m = Wrapper{} }
func (m *Wrapper) String() string            { return proto.CompactTextString(m) }
func (*Wrapper) ProtoMessage()               {}
func (*Wrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *Wrapper) GetIdcode() string {
	if m != nil {
		return m.Idcode
	}
	return ""
}

func (m *Wrapper) GetElement() string {
	if m != nil {
		return m.Element
	}
	return ""
}

func (m *Wrapper) GetAtributes() *Atributes {
	if m != nil {
		return m.Atributes
	}
	return nil
}

func (m *Wrapper) GetAtributesID() string {
	if m != nil {
		return m.AtributesID
	}
	return ""
}

type Atributes struct {
	// @inject_tag: gorm:"primary_key"
	Idcode string `protobuf:"bytes,1,opt,name=idcode" json:"idcode,omitempty" gorm:"primary_key"`
}

func (m *Atributes) Reset()                    { *m = Atributes{} }
func (m *Atributes) String() string            { return proto.CompactTextString(m) }
func (*Atributes) ProtoMessage()               {}
func (*Atributes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *Atributes) GetIdcode() string {
	if m != nil {
		return m.Idcode
	}
	return ""
}

type Form struct {
	// @inject_tag: gorm:"primary_key"
	Idcode string `protobuf:"bytes,1,opt,name=idcode" json:"idcode,omitempty" gorm:"primary_key"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// @inject_tag: `gorm:"DEFAULT:false"`
	Multiline bool `protobuf:"varint,5,opt,name=multiline" json:"multiline,omitempty" gorm:"DEFAULT:false"`
	// @inject_tag: `gorm:"foreignkey:FormRefer"`
	Fields []*FormSchema `protobuf:"bytes,3,rep,name=fields" json:"fields,omitempty" gorm:"foreignkey:FormRefer"`
	// @inject_tag: gorm:"many2many:form_childrens;foreignkey:idcode;association_foreignkey:idcode;association_jointable_foreignkey:children_idcode;jointable_foreignkey:parent_idcode;"
	Tabs []*Form `protobuf:"bytes,4,rep,name=tabs" json:"tabs,omitempty" gorm:"many2many:form_childrens;foreignkey:idcode;association_foreignkey:idcode;association_jointable_foreignkey:children_idcode;jointable_foreignkey:parent_idcode;"`
}

func (m *Form) Reset()                    { *m = Form{} }
func (m *Form) String() string            { return proto.CompactTextString(m) }
func (*Form) ProtoMessage()               {}
func (*Form) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *Form) GetIdcode() string {
	if m != nil {
		return m.Idcode
	}
	return ""
}

func (m *Form) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Form) GetMultiline() bool {
	if m != nil {
		return m.Multiline
	}
	return false
}

func (m *Form) GetFields() []*FormSchema {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *Form) GetTabs() []*Form {
	if m != nil {
		return m.Tabs
	}
	return nil
}

type FormSchema struct {
	// @inject_tag: `gorm:""default:'none'""`//Type of field
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	// @inject_tag: `gorm:""default:'none'""`//Label of field
	Label string `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	// @inject_tag: `gorm:""default:'none'""`//Name of property in the model
	Model string `protobuf:"bytes,3,opt,name=model" json:"model,omitempty"`
	// @inject_tag: `gorm:"primary_key"`//idcode of the field. If not set, will be auto-generated from the slugified version of either: schema.inputName, schema.label or schema.model, in that order. If the fieldIdPrefix option is set, it's value will be prepended to both manual & auto-generated ids.
	Idcode string `protobuf:"bytes,4,opt,name=idcode" json:"idcode,omitempty" gorm:"primary_key"`
	// @inject_tag: `gorm:""default:'false'""`//is it a featured (bold) field? It can be a function too.
	Featured bool `protobuf:"varint,5,opt,name=featured" json:"featured,omitempty"`
	// @inject_tag: `gorm:""default:'true'""`//if false, field will be hidden. It can be a function too.
	Visible bool `protobuf:"varint,6,opt,name=visible" json:"visible,omitempty"`
	// @inject_tag: `gorm:""default:'false'""`//if true, field will be disabled. It can be a function too.
	Disabled bool `protobuf:"varint,7,opt,name=disabled" json:"disabled,omitempty"`
	// @inject_tag: `gorm:""default:'false'""`//if true, must be fill this field (need to use validator).
	Required bool `protobuf:"varint,8,opt,name=required" json:"required,omitempty"`
	// @inject_tag: `gorm:""default:'false'""`//if true, it will visible only if multiple is true in component attributes
	Multi bool `protobuf:"varint,9,opt,name=multi" json:"multi,omitempty"`
	// @inject_tag: `gorm:""default:'none'""`//Default value of the field (use when create a new model)
	Default string `protobuf:"bytes,10,opt,name=default" json:"default,omitempty"`
	// @inject_tag: `gorm:""default:'none'""`//show this hint below the field
	Hint string `protobuf:"bytes,11,opt,name=hint" json:"hint,omitempty"`
	// @inject_tag: `gorm:""default:'none'""`//set name attribute to input field. You can use it to generate normal HTML Forms and submit the field values to server-side. Example
	InputName string `protobuf:"bytes,12,opt,name=inputName" json:"inputName,omitempty"`
	// @inject_tag: `gorm:""default:'none'""`//show this help if mouse hover the question icon before the caption of field. You can use HTML elements too.
	Help string `protobuf:"bytes,13,opt,name=help" json:"help,omitempty"`
	// @inject_tag: `gorm:"many2many:schema_validator;foreignkey:idcode;association_foreignkey:idcode;association_jointable_foreignkey:validator_idcode;jointable_foreignkey:schema_idcode;"default:'none'""`//Validator for value. It can be an array of functions too.
	Validator string `protobuf:"bytes,14,opt,name=validator" json:"validator,omitempty" gorm:"many2many:schema_validator;foreignkey:idcode;association_foreignkey:idcode;association_jointable_foreignkey:validator_idcode;jointable_foreignkey:schema_idcode;"`
	// @inject_tag: `gorm:"many2many:schema_classes;foreignkey:idcode;association_foreignkey:idcode;association_jointable_foreignkey:class_idcode;jointable_foreignkey:schema_idcode;"default:'none'""`//custom css style classes. It will be appended to the .from-group
	StyleClasses []*Class `protobuf:"bytes,15,rep,name=styleClasses" json:"styleClasses,omitempty" gorm:"many2many:schema_classes;foreignkey:idcode;association_foreignkey:idcode;association_jointable_foreignkey:class_idcode;jointable_foreignkey:schema_idcode;"`
	// @inject_tag: `gorm:"many2many:schema_buttons;foreignkey:idcode;association_foreignkey:idcode;association_jointable_foreignkey:button_idcode;jointable_foreignkey:schema_idcode;"default:'none'""`//Array of button objects. This is useful if you need some helper function to fill the field. (E.g. generate password, get GPS location..etc)*
	Buttons     []*Buttons `protobuf:"bytes,16,rep,name=buttons" json:"buttons,omitempty" gorm:"many2many:schema_buttons;foreignkey:idcode;association_foreignkey:idcode;association_jointable_foreignkey:button_idcode;jointable_foreignkey:schema_idcode;"`
	FormRefer   string     `protobuf:"bytes,17,opt,name=FormRefer" json:"FormRefer,omitempty"`
	OnChanged   string     `protobuf:"bytes,18,opt,name=onChanged" json:"onChanged,omitempty"`
	OnValidated string     `protobuf:"bytes,19,opt,name=onValidated" json:"onValidated,omitempty"`
	Get         string     `protobuf:"bytes,20,opt,name=get" json:"get,omitempty"`
	Set         string     `protobuf:"bytes,21,opt,name=set" json:"set,omitempty"`
	InputType   string     `protobuf:"bytes,22,opt,name=inputType" json:"inputType,omitempty"`
	Width       int32      `protobuf:"varint,23,opt,name=width" json:"width,omitempty"`
	Offset      int32      `protobuf:"varint,24,opt,name=offset" json:"offset,omitempty"`
	Xs          int32      `protobuf:"varint,25,opt,name=xs" json:"xs,omitempty"`
	Sm          int32      `protobuf:"varint,26,opt,name=sm" json:"sm,omitempty"`
	Md          int32      `protobuf:"varint,27,opt,name=md" json:"md,omitempty"`
	Lg          int32      `protobuf:"varint,28,opt,name=lg" json:"lg,omitempty"`
	XsOffset    int32      `protobuf:"varint,29,opt,name=xs_offset,json=xsOffset" json:"xs_offset,omitempty"`
	SmOffset    int32      `protobuf:"varint,30,opt,name=sm_offset,json=smOffset" json:"sm_offset,omitempty"`
	MdOffset    int32      `protobuf:"varint,31,opt,name=md_offset,json=mdOffset" json:"md_offset,omitempty"`
	LgOffset    int32      `protobuf:"varint,32,opt,name=lg_offset,json=lgOffset" json:"lg_offset,omitempty"`
	Order       int32      `protobuf:"varint,33,opt,name=order" json:"order,omitempty"`
	// @inject_tag: `gorm:"foreignkey:SchemaRefer;association_foreignkey:idcode"`
	Selectoptions *SelectOptions `protobuf:"bytes,34,opt,name=selectoptions" json:"selectoptions,omitempty" gorm:"foreignkey:SchemaRefer;association_foreignkey:idcode"`
	// @inject_tag: `gorm:"foreignkey:SchemaRefer;association_foreignkey:idcode"`
	Values []*Values `protobuf:"bytes,45,rep,name=values" json:"values,omitempty" gorm:"foreignkey:SchemaRefer;association_foreignkey:idcode"`
	Rules  []*Rules  `protobuf:"bytes,46,rep,name=rules" json:"rules,omitempty"`
}

func (m *FormSchema) Reset()                    { *m = FormSchema{} }
func (m *FormSchema) String() string            { return proto.CompactTextString(m) }
func (*FormSchema) ProtoMessage()               {}
func (*FormSchema) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *FormSchema) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FormSchema) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *FormSchema) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *FormSchema) GetIdcode() string {
	if m != nil {
		return m.Idcode
	}
	return ""
}

func (m *FormSchema) GetFeatured() bool {
	if m != nil {
		return m.Featured
	}
	return false
}

func (m *FormSchema) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

func (m *FormSchema) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *FormSchema) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *FormSchema) GetMulti() bool {
	if m != nil {
		return m.Multi
	}
	return false
}

func (m *FormSchema) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *FormSchema) GetHint() string {
	if m != nil {
		return m.Hint
	}
	return ""
}

func (m *FormSchema) GetInputName() string {
	if m != nil {
		return m.InputName
	}
	return ""
}

func (m *FormSchema) GetHelp() string {
	if m != nil {
		return m.Help
	}
	return ""
}

func (m *FormSchema) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *FormSchema) GetStyleClasses() []*Class {
	if m != nil {
		return m.StyleClasses
	}
	return nil
}

func (m *FormSchema) GetButtons() []*Buttons {
	if m != nil {
		return m.Buttons
	}
	return nil
}

func (m *FormSchema) GetFormRefer() string {
	if m != nil {
		return m.FormRefer
	}
	return ""
}

func (m *FormSchema) GetOnChanged() string {
	if m != nil {
		return m.OnChanged
	}
	return ""
}

func (m *FormSchema) GetOnValidated() string {
	if m != nil {
		return m.OnValidated
	}
	return ""
}

func (m *FormSchema) GetGet() string {
	if m != nil {
		return m.Get
	}
	return ""
}

func (m *FormSchema) GetSet() string {
	if m != nil {
		return m.Set
	}
	return ""
}

func (m *FormSchema) GetInputType() string {
	if m != nil {
		return m.InputType
	}
	return ""
}

func (m *FormSchema) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *FormSchema) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FormSchema) GetXs() int32 {
	if m != nil {
		return m.Xs
	}
	return 0
}

func (m *FormSchema) GetSm() int32 {
	if m != nil {
		return m.Sm
	}
	return 0
}

func (m *FormSchema) GetMd() int32 {
	if m != nil {
		return m.Md
	}
	return 0
}

func (m *FormSchema) GetLg() int32 {
	if m != nil {
		return m.Lg
	}
	return 0
}

func (m *FormSchema) GetXsOffset() int32 {
	if m != nil {
		return m.XsOffset
	}
	return 0
}

func (m *FormSchema) GetSmOffset() int32 {
	if m != nil {
		return m.SmOffset
	}
	return 0
}

func (m *FormSchema) GetMdOffset() int32 {
	if m != nil {
		return m.MdOffset
	}
	return 0
}

func (m *FormSchema) GetLgOffset() int32 {
	if m != nil {
		return m.LgOffset
	}
	return 0
}

func (m *FormSchema) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *FormSchema) GetSelectoptions() *SelectOptions {
	if m != nil {
		return m.Selectoptions
	}
	return nil
}

func (m *FormSchema) GetValues() []*Values {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *FormSchema) GetRules() []*Rules {
	if m != nil {
		return m.Rules
	}
	return nil
}

type Buttons struct {
	// @inject_tag: gorm:"primary_key"
	Idcode  string `protobuf:"bytes,1,opt,name=idcode" json:"idcode,omitempty" gorm:"primary_key"`
	Classes string `protobuf:"bytes,2,opt,name=classes" json:"classes,omitempty"`
	Label   string `protobuf:"bytes,3,opt,name=label" json:"label,omitempty"`
	Onclick string `protobuf:"bytes,4,opt,name=onclick" json:"onclick,omitempty"`
}

func (m *Buttons) Reset()                    { *m = Buttons{} }
func (m *Buttons) String() string            { return proto.CompactTextString(m) }
func (*Buttons) ProtoMessage()               {}
func (*Buttons) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *Buttons) GetIdcode() string {
	if m != nil {
		return m.Idcode
	}
	return ""
}

func (m *Buttons) GetClasses() string {
	if m != nil {
		return m.Classes
	}
	return ""
}

func (m *Buttons) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Buttons) GetOnclick() string {
	if m != nil {
		return m.Onclick
	}
	return ""
}

type Class struct {
	Class string `protobuf:"bytes,2,opt,name=class" json:"class,omitempty"`
}

func (m *Class) Reset()                    { *m = Class{} }
func (m *Class) String() string            { return proto.CompactTextString(m) }
func (*Class) ProtoMessage()               {}
func (*Class) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *Class) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

type SelectOptions struct {
	// @inject_tag: gorm:"primary_key"
	Idcode         string `protobuf:"bytes,1,opt,name=idcode" json:"idcode,omitempty" gorm:"primary_key"`
	Multiple       bool   `protobuf:"varint,3,opt,name=multiple" json:"multiple,omitempty"`
	Searchable     bool   `protobuf:"varint,4,opt,name=searchable" json:"searchable,omitempty"`
	ClearOnSelect  bool   `protobuf:"varint,5,opt,name=clearOnSelect" json:"clearOnSelect,omitempty"`
	HideSelected   bool   `protobuf:"varint,6,opt,name=hideSelected" json:"hideSelected,omitempty"`
	Taggable       bool   `protobuf:"varint,7,opt,name=taggable" json:"taggable,omitempty"`
	TagPlaceholder string `protobuf:"bytes,2,opt,name=tagPlaceholder" json:"tagPlaceholder,omitempty"`
	OnNewTag       string `protobuf:"bytes,8,opt,name=onNewTag" json:"onNewTag,omitempty"`
	OnSearch       string `protobuf:"bytes,9,opt,name=onSearch" json:"onSearch,omitempty"`
	SchemaRefer    string `protobuf:"bytes,10,opt,name=SchemaRefer" json:"SchemaRefer,omitempty"`
	Value          string `protobuf:"bytes,11,opt,name=value" json:"value,omitempty"`
}

func (m *SelectOptions) Reset()                    { *m = SelectOptions{} }
func (m *SelectOptions) String() string            { return proto.CompactTextString(m) }
func (*SelectOptions) ProtoMessage()               {}
func (*SelectOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *SelectOptions) GetIdcode() string {
	if m != nil {
		return m.Idcode
	}
	return ""
}

func (m *SelectOptions) GetMultiple() bool {
	if m != nil {
		return m.Multiple
	}
	return false
}

func (m *SelectOptions) GetSearchable() bool {
	if m != nil {
		return m.Searchable
	}
	return false
}

func (m *SelectOptions) GetClearOnSelect() bool {
	if m != nil {
		return m.ClearOnSelect
	}
	return false
}

func (m *SelectOptions) GetHideSelected() bool {
	if m != nil {
		return m.HideSelected
	}
	return false
}

func (m *SelectOptions) GetTaggable() bool {
	if m != nil {
		return m.Taggable
	}
	return false
}

func (m *SelectOptions) GetTagPlaceholder() string {
	if m != nil {
		return m.TagPlaceholder
	}
	return ""
}

func (m *SelectOptions) GetOnNewTag() string {
	if m != nil {
		return m.OnNewTag
	}
	return ""
}

func (m *SelectOptions) GetOnSearch() string {
	if m != nil {
		return m.OnSearch
	}
	return ""
}

func (m *SelectOptions) GetSchemaRefer() string {
	if m != nil {
		return m.SchemaRefer
	}
	return ""
}

func (m *SelectOptions) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Values struct {
	// @inject_tag: gorm:"primary_key"
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" gorm:"primary_key"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	SchemaRefer string `protobuf:"bytes,3,opt,name=SchemaRefer" json:"SchemaRefer,omitempty"`
}

func (m *Values) Reset()                    { *m = Values{} }
func (m *Values) String() string            { return proto.CompactTextString(m) }
func (*Values) ProtoMessage()               {}
func (*Values) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *Values) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Values) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Values) GetSchemaRefer() string {
	if m != nil {
		return m.SchemaRefer
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterType((*Request)(nil), "auth.Request")
	proto.RegisterType((*IsNewDB)(nil), "auth.IsNewDB")
	proto.RegisterType((*ResponseUser)(nil), "auth.ResponseUser")
	proto.RegisterType((*ResponseRole)(nil), "auth.ResponseRole")
	proto.RegisterType((*ResponseMenu)(nil), "auth.ResponseMenu")
	proto.RegisterType((*ResponseRule)(nil), "auth.ResponseRule")
	proto.RegisterType((*ResponseForm)(nil), "auth.ResponseForm")
	proto.RegisterType((*ResponseFormSchema)(nil), "auth.ResponseFormSchema")
	proto.RegisterType((*ResponseToken)(nil), "auth.ResponseToken")
	proto.RegisterType((*Token)(nil), "auth.Token")
	proto.RegisterType((*Error)(nil), "auth.Error")
	proto.RegisterType((*Role)(nil), "auth.Role")
	proto.RegisterType((*Rules)(nil), "auth.Rules")
	proto.RegisterType((*Conditions)(nil), "auth.Conditions")
	proto.RegisterType((*Menu)(nil), "auth.Menu")
	proto.RegisterType((*Badge)(nil), "auth.Badge")
	proto.RegisterType((*Wrapper)(nil), "auth.Wrapper")
	proto.RegisterType((*Atributes)(nil), "auth.Atributes")
	proto.RegisterType((*Form)(nil), "auth.Form")
	proto.RegisterType((*FormSchema)(nil), "auth.FormSchema")
	proto.RegisterType((*Buttons)(nil), "auth.Buttons")
	proto.RegisterType((*Class)(nil), "auth.Class")
	proto.RegisterType((*SelectOptions)(nil), "auth.SelectOptions")
	proto.RegisterType((*Values)(nil), "auth.Values")
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1839 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0xdb, 0x6e, 0x1c, 0xc7,
	0x11, 0xd5, 0xde, 0x77, 0x8b, 0xbb, 0x92, 0xd2, 0xa2, 0x9d, 0x09, 0x25, 0x53, 0xf4, 0xd8, 0xb0,
	0xe5, 0xc4, 0xa2, 0x0c, 0x0a, 0x08, 0xe0, 0xc0, 0x2f, 0x94, 0x18, 0x13, 0x02, 0x22, 0x29, 0x18,
	0xd1, 0x4e, 0xde, 0x82, 0xd9, 0x9d, 0xe2, 0xee, 0x44, 0x73, 0x59, 0x4f, 0xf7, 0x88, 0xd4, 0x3f,
	0xe4, 0x0b, 0x92, 0x87, 0x7c, 0x47, 0x80, 0xe4, 0x27, 0xf2, 0x1c, 0x20, 0xc8, 0x9f, 0x04, 0x55,
	0xd5, 0x73, 0x59, 0xd2, 0xb3, 0x1e, 0xe9, 0x65, 0x77, 0xce, 0xa9, 0xea, 0xae, 0x4b, 0x57, 0x57,
	0xf7, 0x0c, 0x7c, 0xb0, 0xce, 0x52, 0x93, 0x3e, 0xf2, 0x73, 0xb3, 0xe2, 0x9f, 0x43, 0xc6, 0xaa,
	0x4f, 0xcf, 0xee, 0xbf, 0x3b, 0xd0, 0xff, 0x4e, 0x63, 0xa6, 0x3e, 0x84, 0x61, 0x18, 0x2c, 0xd2,
	0x00, 0x9d, 0xce, 0x41, 0xe7, 0xc1, 0xc4, 0xb3, 0x48, 0x29, 0xe8, 0x27, 0x7e, 0x8c, 0x4e, 0x97,
	0x59, 0x7e, 0x56, 0x0e, 0x8c, 0x16, 0x69, 0xbc, 0xf6, 0x93, 0xb7, 0x4e, 0x8f, 0xe9, 0x02, 0xaa,
	0x5d, 0x18, 0x60, 0xec, 0x87, 0x91, 0xd3, 0x67, 0x5e, 0x80, 0xda, 0x83, 0xf1, 0xda, 0xd7, 0xfa,
	0x22, 0xcd, 0x02, 0x67, 0xc0, 0x82, 0x12, 0xd3, 0x08, 0x93, 0xbe, 0xc6, 0xc4, 0x19, 0xca, 0x08,
	0x06, 0xea, 0x00, 0x06, 0x59, 0x1a, 0xa1, 0x76, 0x46, 0x07, 0xbd, 0x07, 0x3b, 0x47, 0x70, 0xc8,
	0x8e, 0x7b, 0x69, 0x84, 0x9e, 0x08, 0x68, 0xce, 0x00, 0x75, 0xb8, 0x4c, 0x30, 0x73, 0xc6, 0x07,
	0x9d, 0x07, 0x63, 0xaf, 0xc4, 0xee, 0x04, 0x46, 0x1e, 0xfe, 0x90, 0xa3, 0x36, 0xee, 0x7d, 0x18,
	0x3d, 0xd3, 0x2f, 0xf0, 0xe2, 0xe4, 0x09, 0x59, 0x0a, 0x75, 0x82, 0x17, 0x1c, 0xe0, 0xd8, 0x13,
	0xe0, 0xfe, 0xb7, 0x03, 0x53, 0x0f, 0xf5, 0x3a, 0x4d, 0x34, 0x72, 0x22, 0xf6, 0xa1, 0x9f, 0x6b,
	0xcc, 0x58, 0xab, 0xb4, 0x4c, 0x12, 0x8f, 0x79, 0x72, 0x8d, 0xfe, 0xb5, 0xd3, 0xad, 0xbb, 0xc6,
	0x0a, 0x22, 0x50, 0x9f, 0xc0, 0x10, 0xb3, 0x2c, 0xcd, 0xb4, 0xd3, 0x63, 0x95, 0x1d, 0x51, 0xf9,
	0x2d, 0x71, 0x9e, 0x15, 0xa9, 0x8f, 0x8b, 0xb8, 0xfb, 0x6c, 0xc7, 0xea, 0x9c, 0x11, 0x55, 0x24,
	0xc1, 0x85, 0x61, 0x8c, 0x49, 0x8e, 0xda, 0x19, 0xd4, 0x4d, 0x3d, 0xc7, 0x24, 0xf7, 0xac, 0x84,
	0xa6, 0xc9, 0x72, 0x4a, 0xd4, 0xb0, 0x6e, 0xca, 0x23, 0xca, 0x13, 0x89, 0x9b, 0x57, 0x01, 0x52,
	0x02, 0x29, 0x40, 0x4a, 0xe1, 0x66, 0x80, 0x9c, 0x5a, 0xe6, 0xab, 0xdc, 0x77, 0x9b, 0x72, 0xdf,
	0x26, 0x40, 0xf7, 0xa2, 0x32, 0x4b, 0x1e, 0x93, 0x59, 0xf2, 0x79, 0xd3, 0x2c, 0xc7, 0xc2, 0x7c,
	0x2d, 0xda, 0x6e, 0x63, 0xb4, 0xef, 0x6a, 0x98, 0xf2, 0xa0, 0xee, 0x43, 0x9f, 0x12, 0x61, 0x0d,
	0x6f, 0x64, 0x88, 0x05, 0x55, 0x0e, 0xbb, 0x4d, 0x39, 0x6c, 0x67, 0xb8, 0x96, 0xe8, 0x6f, 0xd3,
	0x2c, 0xa6, 0x88, 0xcf, 0xd3, 0x2c, 0xde, 0x8c, 0x98, 0x24, 0x1e, 0xf3, 0x94, 0x68, 0xfa, 0xbf,
	0x12, 0x30, 0x2b, 0x88, 0xa0, 0x9d, 0xd9, 0xbf, 0x77, 0x40, 0xd5, 0xed, 0xbe, 0x5a, 0xac, 0x30,
	0xf6, 0xd5, 0x57, 0x00, 0x3c, 0x09, 0x23, 0xeb, 0xc3, 0xed, 0xca, 0x84, 0x68, 0x79, 0x35, 0x1d,
	0x75, 0x04, 0x3b, 0x15, 0x2a, 0xbc, 0xba, 0x3e, 0xa4, 0xae, 0xd4, 0x76, 0x45, 0x66, 0x85, 0x83,
	0x5c, 0xe0, 0x55, 0xf1, 0x77, 0x1a, 0x8b, 0xbf, 0xd8, 0x86, 0xdd, 0x86, 0x6d, 0xd8, 0xca, 0xf0,
	0x1f, 0x61, 0x20, 0x06, 0x77, 0xeb, 0x06, 0xcb, 0x2e, 0xb3, 0x0b, 0x83, 0x37, 0x7e, 0x14, 0x06,
	0x6c, 0x64, 0xec, 0x09, 0x68, 0x37, 0xf3, 0x31, 0x0c, 0x98, 0xb8, 0xd2, 0x37, 0x07, 0x65, 0xdf,
	0x3c, 0x80, 0x9d, 0x00, 0xf5, 0x22, 0x0b, 0xd7, 0x26, 0x4c, 0x13, 0xdb, 0x3e, 0xeb, 0x94, 0xfb,
	0xb7, 0x0e, 0xf4, 0x79, 0x43, 0xbe, 0x4b, 0xeb, 0x2d, 0xbb, 0x4f, 0xaf, 0xa9, 0xfb, 0x54, 0xfb,
	0xa8, 0xff, 0xd3, 0x5d, 0x63, 0xd0, 0xd8, 0x35, 0xfe, 0xd5, 0x81, 0x01, 0x13, 0x8d, 0xee, 0x39,
	0x30, 0xf2, 0x17, 0x14, 0x89, 0xb6, 0x1e, 0x16, 0x90, 0x24, 0x3a, 0x9f, 0xff, 0x19, 0x17, 0xa6,
	0x38, 0x1f, 0x2c, 0xa4, 0xb9, 0xce, 0x43, 0x8c, 0x02, 0x6d, 0x0f, 0x08, 0x8b, 0xa8, 0x58, 0x17,
	0x69, 0x12, 0x84, 0x32, 0xdd, 0xa0, 0x5e, 0xac, 0x4f, 0x4b, 0xde, 0xab, 0xe9, 0xa8, 0x7d, 0x00,
	0x6e, 0x46, 0x19, 0x9e, 0x63, 0x66, 0x0f, 0x8f, 0x1a, 0xe3, 0x9e, 0x00, 0x54, 0x23, 0x1b, 0x63,
	0xd8, 0xdf, 0xb0, 0x4b, 0x15, 0x3f, 0xa9, 0x5b, 0x71, 0xff, 0xd9, 0x85, 0x3e, 0x77, 0xaf, 0x77,
	0x59, 0xa3, 0xdb, 0xd0, 0xcb, 0xb3, 0xc8, 0x86, 0x4e, 0x8f, 0x94, 0xef, 0xb9, 0x1f, 0x2c, 0x71,
	0xb3, 0xd9, 0x3f, 0x21, 0xca, 0x13, 0x89, 0xfa, 0x1c, 0x46, 0x17, 0x99, 0xbf, 0x5e, 0x63, 0x66,
	0xc3, 0x9f, 0x89, 0xd2, 0x1f, 0x84, 0xf4, 0x0a, 0x29, 0x97, 0x72, 0x68, 0x22, 0xe4, 0x98, 0xc7,
	0x9e, 0x00, 0xf5, 0x19, 0x8c, 0x17, 0xab, 0x30, 0x0a, 0x32, 0x4c, 0x36, 0xcf, 0x4c, 0x5e, 0xf7,
	0x52, 0x46, 0xfe, 0x86, 0x8b, 0x34, 0xe1, 0x23, 0x73, 0xe2, 0xf1, 0x73, 0xd5, 0xf0, 0x27, 0x4d,
	0x0d, 0xdf, 0x81, 0x11, 0x7b, 0xf9, 0xec, 0xc4, 0x01, 0x59, 0x50, 0x0b, 0xd5, 0x3d, 0x98, 0x58,
	0xc7, 0x9e, 0x9d, 0x38, 0x3b, 0x2c, 0xab, 0x08, 0xf7, 0x39, 0x0c, 0x38, 0xc8, 0x6d, 0x35, 0xf4,
	0xc6, 0xcf, 0x42, 0x3f, 0x31, 0x45, 0x0d, 0x59, 0x48, 0x8e, 0x1a, 0xbc, 0x2c, 0x0a, 0x88, 0x9f,
	0xdd, 0xbf, 0x74, 0x60, 0x64, 0xf3, 0xb1, 0x6d, 0x46, 0x8c, 0x30, 0xc6, 0x6a, 0x46, 0x0b, 0xd5,
	0x43, 0x98, 0xf8, 0x26, 0x0b, 0xe7, 0xb9, 0x41, 0xcd, 0xd3, 0xee, 0x1c, 0xdd, 0x92, 0x50, 0x8f,
	0x0b, 0xda, 0xab, 0x34, 0x68, 0x03, 0x97, 0xe0, 0xd9, 0x89, 0xad, 0xd7, 0x3a, 0xe5, 0x7e, 0x02,
	0x93, 0x72, 0x64, 0x93, 0x3f, 0xee, 0x5f, 0x3b, 0xd0, 0xe7, 0xd3, 0xe0, 0x5d, 0x2a, 0xe8, 0x1e,
	0x4c, 0xe2, 0x3c, 0x32, 0x61, 0x14, 0x26, 0xc8, 0xe5, 0x30, 0xf6, 0x2a, 0x42, 0x3d, 0x28, 0x37,
	0x51, 0xaf, 0xa1, 0x45, 0x17, 0xdb, 0x6a, 0x1f, 0xfa, 0xc6, 0x9f, 0x5f, 0xe9, 0x04, 0x72, 0x02,
	0x11, 0xef, 0xfe, 0x67, 0x04, 0x50, 0x3b, 0x32, 0x28, 0xe7, 0x6f, 0xd7, 0x85, 0x83, 0xfc, 0x4c,
	0xe5, 0x16, 0xf9, 0x73, 0x8c, 0xac, 0x7f, 0x02, 0x88, 0x8d, 0xd3, 0x00, 0x8b, 0x22, 0x17, 0x50,
	0x0b, 0xb1, 0xbf, 0x11, 0xe2, 0x1e, 0x8c, 0xcf, 0xd1, 0x37, 0x79, 0x86, 0x81, 0x8d, 0xa6, 0xc4,
	0x5c, 0x01, 0xa1, 0x0e, 0xe7, 0x65, 0x41, 0x17, 0x90, 0x6f, 0x78, 0xa1, 0xf6, 0xe7, 0x11, 0x06,
	0xce, 0xc8, 0xde, 0xf0, 0x2c, 0x26, 0x59, 0x86, 0x3f, 0xe4, 0x21, 0xcd, 0x68, 0x6f, 0x7f, 0x05,
	0x66, 0xdf, 0x28, 0x57, 0xce, 0x44, 0x36, 0x08, 0x03, 0xb2, 0x13, 0xe0, 0xb9, 0x9f, 0x47, 0xa6,
	0x28, 0x61, 0x0b, 0x29, 0xea, 0x55, 0x98, 0x18, 0x5b, 0xbd, 0xfc, 0x4c, 0x0b, 0x10, 0x26, 0xeb,
	0xdc, 0xbc, 0xa0, 0x95, 0x99, 0x4a, 0x59, 0x97, 0x04, 0x8f, 0xc0, 0x68, 0xed, 0xcc, 0xec, 0x08,
	0x8c, 0xd6, 0x34, 0x82, 0x8f, 0x0f, 0xdf, 0xa4, 0x99, 0x73, 0x53, 0x46, 0x94, 0x84, 0x7a, 0x04,
	0x53, 0x6d, 0xde, 0x46, 0xf8, 0x34, 0xf2, 0xb5, 0x46, 0xed, 0xdc, 0xaa, 0xf7, 0x5d, 0x26, 0xbd,
	0x0d, 0x05, 0x6a, 0x07, 0xf3, 0xdc, 0x18, 0xea, 0x4a, 0xb7, 0x59, 0xd7, 0xb6, 0x83, 0x27, 0x42,
	0x7a, 0x85, 0x94, 0xec, 0xf2, 0x82, 0x72, 0x1b, 0xfc, 0x99, 0xd8, 0x2d, 0x09, 0x92, 0xa6, 0xc9,
	0xd3, 0x95, 0x9f, 0x2c, 0x31, 0x70, 0x94, 0x48, 0x4b, 0x82, 0x4a, 0x3c, 0x4d, 0xbe, 0x17, 0x27,
	0x31, 0x70, 0xee, 0x48, 0x89, 0xd7, 0x28, 0x6a, 0x65, 0x4b, 0x34, 0xce, 0xae, 0xb4, 0xb2, 0x25,
	0x1a, 0x62, 0x34, 0x1a, 0xe7, 0x03, 0x61, 0x34, 0x56, 0xb9, 0x3a, 0xa3, 0xd2, 0xf9, 0xb0, 0x96,
	0xab, 0x33, 0x5b, 0x3f, 0x17, 0x61, 0x60, 0x56, 0xce, 0xcf, 0xf9, 0x78, 0x14, 0x40, 0x95, 0x92,
	0x9e, 0x9f, 0xd3, 0x44, 0x8e, 0x9c, 0x9a, 0x82, 0xd4, 0x4d, 0xe8, 0x5e, 0x6a, 0xe7, 0x17, 0xcc,
	0x75, 0x2f, 0x35, 0x61, 0x1d, 0x3b, 0x7b, 0x82, 0x75, 0x4c, 0x38, 0x0e, 0x9c, 0xbb, 0x82, 0xe3,
	0x80, 0x70, 0xb4, 0x74, 0xee, 0x09, 0x8e, 0x96, 0xea, 0x2e, 0x4c, 0x2e, 0xf5, 0x9f, 0xec, 0xd4,
	0x1f, 0x31, 0x3d, 0xbe, 0xd4, 0x2f, 0x65, 0xf2, 0xbb, 0x30, 0xd1, 0x71, 0x21, 0xdc, 0x17, 0xa1,
	0x8e, 0x2b, 0x61, 0x1c, 0x14, 0xc2, 0xfb, 0x22, 0x8c, 0x83, 0x4a, 0x18, 0x2d, 0x0b, 0xe1, 0x81,
	0x08, 0xa3, 0xa5, 0x15, 0xee, 0xc2, 0x20, 0xcd, 0x02, 0xcc, 0x9c, 0x8f, 0x25, 0x42, 0x06, 0xea,
	0x6b, 0x98, 0x69, 0x8c, 0x70, 0x61, 0xd2, 0xb5, 0x1c, 0x2e, 0x2e, 0x77, 0x9c, 0x3b, 0xb2, 0x8c,
	0xaf, 0x58, 0xf4, 0x52, 0x44, 0xde, 0xa6, 0xa6, 0xfa, 0x14, 0x86, 0x6f, 0xfc, 0x88, 0x4e, 0xf0,
	0x87, 0xbc, 0xf4, 0x53, 0x19, 0xf3, 0x3d, 0x73, 0x9e, 0x95, 0x55, 0x67, 0xf8, 0x61, 0xe3, 0x19,
	0xfe, 0x1a, 0x46, 0xb6, 0x5e, 0xb6, 0xb5, 0xcb, 0x85, 0xad, 0x49, 0xdb, 0x2e, 0x2d, 0xac, 0x36,
	0x7e, 0xaf, 0xbe, 0xf1, 0x1d, 0x18, 0xa5, 0xc9, 0x22, 0x0a, 0x17, 0xaf, 0xed, 0x1e, 0x2f, 0xa0,
	0xfb, 0x11, 0x0c, 0xb8, 0x78, 0x69, 0x20, 0xcf, 0x51, 0x74, 0x0c, 0x06, 0xee, 0xff, 0xba, 0x30,
	0xdb, 0x88, 0xba, 0xd1, 0xa5, 0x3d, 0x18, 0xf3, 0x96, 0x5d, 0x47, 0xc8, 0xb6, 0xc7, 0x5e, 0x89,
	0xe9, 0xbc, 0xd6, 0xe8, 0x67, 0x8b, 0x15, 0xb5, 0x01, 0xf6, 0x60, 0xec, 0xd5, 0x18, 0xf5, 0x29,
	0xcc, 0x16, 0x11, 0xfa, 0xd9, 0xcb, 0x44, 0x6c, 0xd9, 0x76, 0xb3, 0x49, 0x2a, 0x17, 0xa6, 0xab,
	0x30, 0x40, 0x41, 0x18, 0xd8, 0xc6, 0xb3, 0xc1, 0x91, 0x17, 0xc6, 0x5f, 0x2e, 0xd9, 0x8e, 0xed,
	0x3e, 0x05, 0x56, 0x9f, 0xc1, 0x4d, 0xe3, 0x2f, 0x7f, 0x1f, 0xf9, 0x0b, 0x5c, 0xa5, 0x51, 0x60,
	0x6f, 0xa9, 0x13, 0xef, 0x0a, 0x4b, 0x73, 0xa4, 0xc9, 0x0b, 0xbc, 0x38, 0xf3, 0x97, 0xf6, 0xc0,
	0x2d, 0xb1, 0xc8, 0x5e, 0xb1, 0xe7, 0xdc, 0xa8, 0x58, 0x26, 0x98, 0xf6, 0xa5, 0x6d, 0xe4, 0xbc,
	0xab, 0xa5, 0x5f, 0xd5, 0x29, 0x7b, 0x73, 0xcd, 0xd1, 0x36, 0x2d, 0x01, 0xee, 0x0b, 0x18, 0x4a,
	0x91, 0xd0, 0xbe, 0x08, 0x03, 0x9b, 0xd7, 0x6e, 0x18, 0x34, 0x5c, 0x25, 0x37, 0xac, 0xf4, 0xae,
	0x59, 0x39, 0xfa, 0xc7, 0x0c, 0xfa, 0xc7, 0xb9, 0x59, 0xa9, 0x5f, 0xc2, 0xf0, 0x69, 0x86, 0xbe,
	0x41, 0x55, 0xbb, 0x70, 0xee, 0x29, 0x5b, 0x72, 0xb5, 0xb7, 0x67, 0xf7, 0x86, 0xfa, 0x1c, 0x7a,
	0xa7, 0x68, 0x5a, 0x28, 0x3e, 0x84, 0xe1, 0x29, 0x9a, 0xe3, 0x28, 0x52, 0xb3, 0x42, 0xce, 0xef,
	0xec, 0x0d, 0xea, 0xbf, 0x86, 0x5b, 0xa2, 0x4e, 0x58, 0xf3, 0xc5, 0xb9, 0xd5, 0xb8, 0x2f, 0x6c,
	0x0c, 0x75, 0x87, 0xee, 0x6c, 0x6a, 0xf2, 0x3b, 0x82, 0x7b, 0x43, 0x1d, 0x02, 0x7c, 0xb7, 0xa6,
	0xc6, 0xc7, 0x1f, 0x02, 0x7e, 0x3a, 0x82, 0x43, 0x80, 0x13, 0x8c, 0xb0, 0xb5, 0xfe, 0x57, 0x30,
	0x3d, 0x45, 0x43, 0x80, 0x6e, 0x65, 0x7a, 0xdb, 0x08, 0x52, 0xd8, 0x18, 0x21, 0x77, 0xf1, 0x2d,
	0x23, 0x48, 0x81, 0xc3, 0x1d, 0xfc, 0x2e, 0x5d, 0x86, 0x49, 0x0b, 0x77, 0x1e, 0xc3, 0xac, 0xe8,
	0xf4, 0xf2, 0x96, 0x54, 0x7f, 0x0f, 0x6b, 0xce, 0xd1, 0x84, 0x86, 0xff, 0xc8, 0x80, 0xc6, 0x1c,
	0x49, 0xe9, 0xf0, 0x8a, 0xd5, 0xee, 0x96, 0xd7, 0xfc, 0x4f, 0xd9, 0xff, 0x43, 0x80, 0x9c, 0xd7,
	0xa0, 0xa5, 0xfe, 0xaf, 0x60, 0x74, 0x8a, 0xa6, 0xa5, 0xf2, 0x11, 0xec, 0x48, 0x0d, 0x79, 0x7c,
	0xad, 0xdd, 0x5e, 0x3f, 0x95, 0x43, 0x01, 0x2f, 0x72, 0xfb, 0x00, 0x24, 0x60, 0x7e, 0x6f, 0xa8,
	0xdd, 0xc2, 0x1b, 0x96, 0xb8, 0x2c, 0xba, 0x96, 0xfa, 0x12, 0x70, 0x4b, 0xe5, 0xc7, 0x5c, 0x3f,
	0xc7, 0x51, 0xf4, 0x5c, 0x5e, 0xfc, 0xb6, 0x47, 0x5c, 0x79, 0x24, 0x11, 0xf0, 0xbd, 0xb5, 0x76,
	0x6b, 0xbc, 0xaa, 0x4f, 0x5c, 0xe9, 0x51, 0x4b, 0xe5, 0x32, 0xdc, 0xf6, 0xfa, 0xb2, 0xc7, 0x5a,
	0xea, 0x97, 0x4b, 0xfc, 0x2d, 0x7f, 0x41, 0xd9, 0x1e, 0xb0, 0x1d, 0xf3, 0x05, 0x4c, 0xad, 0x0d,
	0xb9, 0x36, 0xd7, 0xad, 0xd4, 0xdf, 0xfe, 0xb9, 0xbb, 0x59, 0x77, 0xce, 0xfc, 0xf9, 0x56, 0xc5,
	0x6f, 0x60, 0x2a, 0x49, 0xb4, 0x77, 0xeb, 0x6b, 0x97, 0xf4, 0x3d, 0xe7, 0xba, 0x2f, 0x22, 0x71,
	0x6f, 0xa8, 0xaf, 0x61, 0x72, 0x8a, 0xe6, 0xbd, 0x86, 0x7e, 0x03, 0x53, 0x49, 0xf0, 0x7b, 0x8d,
	0x7e, 0x54, 0xa4, 0xa2, 0x71, 0xf4, 0x95, 0x38, 0x7f, 0x03, 0x33, 0xc9, 0xf7, 0x2b, 0xfb, 0x45,
	0xe8, 0x4a, 0xc6, 0xb7, 0x19, 0xfb, 0x12, 0x06, 0xf2, 0x69, 0xb6, 0x55, 0x23, 0xff, 0x12, 0xe0,
	0x14, 0x4d, 0xf1, 0x35, 0xf7, 0xca, 0x10, 0x0b, 0xad, 0xd4, 0xbd, 0x31, 0x1f, 0xf2, 0x57, 0xee,
	0xc7, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x27, 0x23, 0x06, 0x5a, 0xfe, 0x16, 0x00, 0x00,
}
